# Site settings
title: Global Internet Magna Carta Project
email: glinmacaorg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Home of the Global Internet Magna Carta Project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://glinmaca.github.io/" # the base hostname & protocol for your site
twitter_username: glinmacaorg
github_username:  glinmaca

# Build settings
markdown: kramdown
